import productsImages from "./constants/productImages";

const products = [
    {
        id: 1,
        name: "GreenDress",
        price: 110,
        category: "dresses",
        rating: 1,
        image: productsImages.greenDress,
        accessory: null,
        quantity: 1,
        description:
            "New look A green cotton summer cutoff sleeve dress for work,parties,everthing!",
    },
    {
        id: 2,
        name: "pinkDress",
        price: 150,
        category: "dresses",
        rating: 2,
        image: productsImages.pinkDress,
        accessory: null,
        quantity: 1,
        description:
            "Greate pink cotton summer cutoff sleeve dress for work,parties,everthing!",
    },
    {
        id: 3,
        name: "blueDress",
        price: 200,
        category: "dresses",
        rating: 3,
        image: productsImages.blueDress,
        accessory: null,
        quantity: 1,
        description:
            "Cool blue cotton summer cutoff sleeve dress for work,parties,everthing!",
    },
    {
        id: 4,
        name: "greenPants",
        price: 40,
        category: "pants",
        rating: 5,
        image: productsImages.greenPant,
        accessory: null,
        quantity: 1,
        description: "A high quality green casual women pant ",
    },
    {
        id: 5,
        name: "blackPants",
        price: 60,
        category: "pants",
        rating: 3.5,
        image: productsImages.blackPant,
        accessory: null,
        quantity: 1,
        description: "A high quality black casual women pant ",
    },
    {
        id: 6,
        name: "brownPants",
        price: 50,
        category: "pants",
        rating: 4,
        image: productsImages.brownPant,
        accessory: null,
        quantity: 1,
        description: "A high quality brown  casual women pant ",
    },
    {
        id: 7,
        name: "whiteShirt",
        price: 60,
        category: "shirts",
        rating: 2,
        image: productsImages.whiteShirt,
        accessory: null,
        quantity: 1,
        description: "A high quality white jeans long sleeve casual women shirt ",
    },
    {
        id: 8,
        name: "blackShirt",
        price: 70,
        category: "shirts",
        rating: 2.5,
        image: productsImages.blackShirt,
        accessory: null,
        quantity: 1,
        description: "A high quality  black jeans long sleeve casual women shirt ",
    },
    {
        id: 9,
        name: "brownShirt",
        price: 80,
        category: "shirts",
        rating: 4,
        image: productsImages.brownShirt,
        accessory: null,
        quantity: 1,
        description: "A high quality  brown jeans long sleeve casual women shirt ",
    },
    {
        id: 10,
        name: "blackWatch",
        price: 60,
        category: null,
        rating: 1,
        image: productsImages.blackwatch,
        accessory: "watches",
        quantity: 1,
        description: "A high quality black watch ",
    },
    {
        id: 11,
        name: "greenwatch",
        price: 80,
        category: null,
        rating: 4,
        image: productsImages.greenWatch,
        accessory: "watches",
        quantity: 3,
        description: "A high quality green  watch ",
    },
    {
        id: 12,
        name: "goldWatch",
        price: 80,
        category: null,
        rating: 4.5,
        image: productsImages.goldWatch,
        accessory: "watches",
        quantity: 1,
        description: "A high quality gold watch ",
    },
    {
        id: 13,
        name: "goldBarcelet",
        price: 70,
        category: null,
        rating: 4,
        image: productsImages.goldBarcelete,
        accessory: "barcelets",
        quantity: 1,
        description: "A high quality gold barcelet ",
    },
    {
        id: 14,
        name: "silverBarcelet",
        price: 80,
        category: null,
        rating: 4,
        image: productsImages.silverBarcelet,
        accessory: "barcelets",
        quantity: 1,
        description: "A high quality sliver barcelet ",
    },
    {
        id: 15,
        name: "diamondNecklace",
        price: 200,
        category: null,
        rating: 3.5,
        image: productsImages.dimondNecklace,
        accessory: "necklaces",
        quantity: 1,
        description: "A high quality dimond necklace ",
    },
    {
        id: 16,
        name: "goldNecklace",
        price: 150,
        category: null,
        rating: 4,
        image: productsImages.goldNecklace,
        accessory: "necklaces",
        quantity: 1,
        description: "A high quality dimond necklace ",
    },
    {
        id: 17,
        name: "whiteBarcelet",
        price: 100,
        category: null,
        rating: 3.5,
        image: productsImages.whiteBarcelet,
        accessory: "barcelets",
        quantity: 1,
        description: "A high quality white barcelet ",
    },
    {
        id: 18,
        name: "silverNecklace",
        price: 120,
        category: null,
        rating: 3,
        image: productsImages.silverNecklace,
        accessory: "necklaces",
        quantity: 1,
        description: "A high quality silver necklace ",
    },
    {
        id: 19,
        name: "goldRing",
        price: 250,
        category: null,
        rating: 4,
        image: productsImages.goldRing,
        accessory: "rings",
        quantity: 1,
        description: "A high quality gold ring ",
    },
    {
        id: 20,
        name: "silverRing",
        price: 100,
        category: null,
        rating: 4.5,
        image: productsImages.silverRing,
        accessory: "rings",
        quantity: 1,
        description: "A high quality silver ring ",
    },
    {
        id: 21,
        name: "blackHat",
        price: 80,
        category: null,
        rating: 4.5,
        image: productsImages.blackHat,
        accessory: "hats",
        quantity: 1,
        description: "A high quality black hat ",
    },
    {
        id: 22,
        name: "GCUIHat",
        price: 200,
        category: null,
        rating: 5,
        image: productsImages.GCUIHat,
        accessory: "hats",
        quantity: 1,
        description: "A high quality GCUI hat ",
    },
    {
        id: 23,
        name: "BrownHat",
        price: 60,
        category: null,
        rating: 2.5,
        image: productsImages.brownHat,
        accessory: "hats",
        quantity: 1,
        description: "A high quality brown hat ",
    },
    {
        id: 24,
        name: "blackBelt",
        price: 10,
        category: null,
        rating: 1.5,
        image: productsImages.blackBelt,
        accessory: "belts",
        quantity: 1,
        description: "A high quality black belt ",
    },
    {
        id: 25,
        name: "greenBelt",
        price: 15,
        category: null,
        rating: 4.5,
        image: productsImages.greenBelt,
        accessory: "belts",
        quantity: 1,
        description: "A high quality brown hat ",
    },
    {
        id: 26,
        name: "brownBelt",
        price: 20,
        category: null,
        rating: 3.5,
        image: productsImages.brownBelt,
        accessory: "belts",
        quantity: 1,
        description: "A high quality brown hat ",
    },
    {
        id: 27,
        name: " diamondRing",
        price: 200,
        category: null,
        rating: 3.5,
        image: productsImages.dimondRing,
        accessory: "rings",
        quantity: 1,
        description: "A high quality dimond ring ",
    },
    {
        id: 28,
        name: "whiteBag",
        price: 25,
        category: null,
        rating: 3.5,
        image: productsImages.whiteBag,
        accessory: "bags",
        quantity: 1,
        description: "A high quality white bag  ",
    },
    {
        id: 29,
        name: "roseBag",
        price: 30,
        category: null,
        rating: 1,
        image: productsImages.roseBag,
        accessory: "bags",
        quantity: 1,
        description: "A high quality rose bag  ",
    },
    {
        id: 30,
        name: "redBag",
        price: 35,
        category: null,
        rating: 2,
        image: productsImages.redBag,
        accessory: "bags",
        quantity: 1,
        description: "A high quality red bag ",
    },
    {
        id: 31,
        name: "yellowBag",
        price: 45,
        category: null,
        rating: 2.5,
        image: productsImages.yellowBag,
        accessory: "bags",
        quantity: 1,
        description: "A high quality yellow bag ",
    },
    {
        id: 32,
        name: "yellowHat",
        price: 45,
        category: null,
        rating: 4,
        image: productsImages.yellowHat,
        accessory: "hats",
        quantity: 1,
        description: "A high quality yellow hat ",
    },
    {
        id: 33,
        name: "whiteNecklace",
        price: 150,
        category: null,
        rating: 4,
        image: productsImages.whiteNecklace,
        accessory: "necklaces",
        quantity: 1,
        description: "A high quality white necklace  ",
    },
    {
        id: 34,
        name: "greenRing",
        price: 80,
        category: null,
        rating: 3,
        image: productsImages.greenRing,
        accessory: "rings",
    },
    {
        id: 35,
        name: "roseWatch",
        price: 70,
        category: null,
        rating: 2.5,
        image: productsImages.roseWatch,
        accessory: "watches",
        quantity: 1,
        description: "A high quality rose watch",
    },
    {
        id: 36,
        name: "brownSkirt",
        price: 170,
        category: "skirts",
        rating: 3.5,
        image: productsImages.brownSkirt,
        accessory: null,
        quantity: 1,
        description: "A high quality brown skirt ",
    },
    {
        id: 37,
        name: "whiteSkirt",
        price: 190,
        category: "skirts",
        rating: 3.5,
        image: productsImages.whiteSkirt,
        accessory: null,
        quantity: 1,
        description: "A high quality white skirt ",
    },
    {
        id: 38,
        name: "whiteSkirt",
        price: 190,
        category: "skirts",
        rating: 3.5,
        image: productsImages.orangeSkirt,
        accessory: null,
        quantity: 1,
        description: "A high quality orange skirt ",
    },
    {
        id: 39,
        name: "blueSkirt",
        price: 130,
        category: "skirts",
        rating: 3,
        image: productsImages.blueSkirt,
        accessory: null,
        quantity: 1,
        description: "A high quality blue skirt ",
    },
    {
        id: 40,
        name: "leatherBlackShirt",
        price: 300,
        category: "shirts",
        rating: 1.5,
        image: productsImages.leatherShirt,
        accessory: null,
        description: "A Nice cutoff sleeve black women leather shirt  ",
        quantity: 1,
    },
    {
        id: 41,
        name: "grayPants",
        price: 80,
        category: "pants",
        rating: 4.5,
        image: productsImages.grayPants,
        accessory: null,
        description: "A high quality gray  casual women pant ",
        quantity: 1,
    },
    {
        id: 42,
        name: "whiteDress",
        price: 60,
        category: "dresses",
        rating: 4.5,
        image: productsImages.whiteDress,
        accessory: null,
        description:
            "New look A pratical white cotton summer cutoff sleeve dress for work, parties, everthing!",
        quantity: 1,
    },
];

export default products;
