export const PRODUCTS_ACTIONS_CONSTANTS = {
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
    SET_FILTER_OPTION: "SET_FILTER_OPTION",
    SET_SORTING_OPTION: "SET_SORTING_OPTION",
    UPDATE_FILTERED_PRODUCTS: "UPDATE_FILTERED_PRODUCTS",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};

export const Cart_ACTIONS_CONSTANTS = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    CLEAR_ALL_ITEMS: "CLEAR_ALL_ITEMS",
    UPDATE_QUANTITY: "UPATE_QUANTITY",
    CLEAR_Error: 'CLEAR_Error',
    CLEAR_SEARCH_QUERY: 'CLEAR_SEARCH_QUERY'
};
