export const PRODUCTS_ACTIONS_CONSTANTS = {
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
    SET_FILTER_OPTION: "SET_FILTER_OPTION",
    SET_SORTING_OPTION: "SET_SORTING_OPTION",
    UPDATE_FILTERED_PRODUCTS: "UPDATE_FILTERED_PRODUCTS",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    PRODUCT_API_FAILURE: "PRODUCT_API_FAILURE",
    PRODUCT_API_REQUEST: "PRODUCT_API_REQUEST",
    PRODUCT_API_SUCCESS: "PRODUCT_API_SUCCESS",
};

export const Cart_ACTIONS_CONSTANTS = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    CLEAR_ALL_ITEMS: "CLEAR_ALL_ITEMS",
    UPDATE_QUANTITY: "UPATE_QUANTITY",
    CLEAR_Error: "CLEAR_Error",
    CLEAR_SEARCH_QUERY: "CLEAR_SEARCH_QUERY",
    UPDATE_SHIPPING_INFO: "UPDATE_SHIPPING_INFO",
    UPDATE_CART_TOTALS: "UPDATE_CART_TOTALS",
    SET_ERROR: 'SET_ERROR'
};

export const AUTH_ACTIONS = {
    LOGIN: "LOGIN",
    Register: "Register",
    LOGOUT: "LOGOUT",
    API_SUCCESS: "API_SUCCESS",
    API_FAILURE: "API_FAILURE",
    API_REQUEST: "API_REQUEST",
    CLEAR_NONINPUTERRORS: "CLEAR_NONINPUTERRORS",
};

export const USER_ACTIONS = {
    UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
};
